# Generated by Django 4.2.13 on 2024-06-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steps',
            options={'verbose_name_plural': 'Steps'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='Null', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
