# Generated by Django 4.2.13 on 2024-06-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeEntry', '0002_alter_steps_options_recipe_image_alter_recipe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='Null', max_length=255),
            preserve_default=False,
        ),
    ]
